//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int ID { get; set; }
        public string HospName { get; set; }
        public string DepartName { get; set; }
        public string DoctorName { get; set; }
        public string DocSex { get; set; }
        public string DocRank { get; set; }
        public string DoctorInro { get; set; }
        public string DocMajor { get; set; }
        public string IsExpert { get; set; }
        public string RegistryFee { get; set; }
        public string ClinicFee { get; set; }
        public string DocPhotoURL { get; set; }
    }
}
