//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace TZHSWEET.Entity
{
    [DataContract(IsReference = true)]
    public partial class VModulePermission: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public string ButtonName
        {
            get { return _buttonName; }
            set
            {
                if (_buttonName != value)
                {
                    _buttonName = value;
                    OnPropertyChanged("ButtonName");
                }
            }
        }
        private string _buttonName;
    
        [DataMember]
        public long ModulePermissionID
        {
            get { return _modulePermissionID; }
            set
            {
                if (_modulePermissionID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“ModulePermissionID”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _modulePermissionID = value;
                    OnPropertyChanged("ModulePermissionID");
                }
            }
        }
        private long _modulePermissionID;
    
        [DataMember]
        public Nullable<int> MenuID
        {
            get { return _menuID; }
            set
            {
                if (_menuID != value)
                {
                    _menuID = value;
                    OnPropertyChanged("MenuID");
                }
            }
        }
        private Nullable<int> _menuID;
    
        [DataMember]
        public Nullable<int> ButtonID
        {
            get { return _buttonID; }
            set
            {
                if (_buttonID != value)
                {
                    _buttonID = value;
                    OnPropertyChanged("ButtonID");
                }
            }
        }
        private Nullable<int> _buttonID;
    
        [DataMember]
        public string MenuName
        {
            get { return _menuName; }
            set
            {
                if (_menuName != value)
                {
                    _menuName = value;
                    OnPropertyChanged("MenuName");
                }
            }
        }
        private string _menuName;
    
        [DataMember]
        public string MenuUrl
        {
            get { return _menuUrl; }
            set
            {
                if (_menuUrl != value)
                {
                    _menuUrl = value;
                    OnPropertyChanged("MenuUrl");
                }
            }
        }
        private string _menuUrl;
    
        [DataMember]
        public string ModuleIcon
        {
            get { return _moduleIcon; }
            set
            {
                if (_moduleIcon != value)
                {
                    _moduleIcon = value;
                    OnPropertyChanged("ModuleIcon");
                }
            }
        }
        private string _moduleIcon;
    
        [DataMember]
        public Nullable<int> ParentNo
        {
            get { return _parentNo; }
            set
            {
                if (_parentNo != value)
                {
                    _parentNo = value;
                    OnPropertyChanged("ParentNo");
                }
            }
        }
        private Nullable<int> _parentNo;
    
        [DataMember]
        public Nullable<byte> Sort
        {
            get { return _sort; }
            set
            {
                if (_sort != value)
                {
                    _sort = value;
                    OnPropertyChanged("Sort");
                }
            }
        }
        private Nullable<byte> _sort;
    
        [DataMember]
        public Nullable<bool> IsLeaf
        {
            get { return _isLeaf; }
            set
            {
                if (_isLeaf != value)
                {
                    _isLeaf = value;
                    OnPropertyChanged("IsLeaf");
                }
            }
        }
        private Nullable<bool> _isLeaf;
    
        [DataMember]
        public Nullable<bool> IsMenu
        {
            get { return _isMenu; }
            set
            {
                if (_isMenu != value)
                {
                    _isMenu = value;
                    OnPropertyChanged("IsMenu");
                }
            }
        }
        private Nullable<bool> _isMenu;
    
        [DataMember]
        public string ModuleController
        {
            get { return _moduleController; }
            set
            {
                if (_moduleController != value)
                {
                    _moduleController = value;
                    OnPropertyChanged("ModuleController");
                }
            }
        }
        private string _moduleController;
    
        [DataMember]
        public string ButtonAction
        {
            get { return _buttonAction; }
            set
            {
                if (_buttonAction != value)
                {
                    _buttonAction = value;
                    OnPropertyChanged("ButtonAction");
                }
            }
        }
        private string _buttonAction;
    
        [DataMember]
        public string ButtonIcon
        {
            get { return _buttonIcon; }
            set
            {
                if (_buttonIcon != value)
                {
                    _buttonIcon = value;
                    OnPropertyChanged("ButtonIcon");
                }
            }
        }
        private string _buttonIcon;
    
        [DataMember]
        public string MenuController
        {
            get { return _menuController; }
            set
            {
                if (_menuController != value)
                {
                    _menuController = value;
                    OnPropertyChanged("MenuController");
                }
            }
        }
        private string _menuController;
    
        [DataMember]
        public Nullable<bool> modPermissionIsDeleted
        {
            get { return _modPermissionIsDeleted; }
            set
            {
                if (_modPermissionIsDeleted != value)
                {
                    _modPermissionIsDeleted = value;
                    OnPropertyChanged("modPermissionIsDeleted");
                }
            }
        }
        private Nullable<bool> _modPermissionIsDeleted;
    
        [DataMember]
        public Nullable<int> ParentID
        {
            get { return _parentID; }
            set
            {
                if (_parentID != value)
                {
                    _parentID = value;
                    OnPropertyChanged("ParentID");
                }
            }
        }
        private Nullable<int> _parentID;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion
    }
}
