//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depart
    {
        public string HospName { get; set; }
        public string DepartName { get; set; }
        public string DepartType { get; set; }
        public string DepartIntro { get; set; }
        public string Limited { get; set; }
        public string RegistryFee { get; set; }
        public string ClinicFee { get; set; }
        public string DepartSex { get; set; }
        public string ChildAge { get; set; }
    }
}
