//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYZJ.HM3Shop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public ActionInfo()
        {
            this.RequestHttpType = "\"Get\"";
            this.ActionType = 0;
            this.Role = new HashSet<Role>();
            this.R_UserInfo_ActionInfo = new HashSet<R_UserInfo_ActionInfo>();
            this.ActionGroup = new HashSet<ActionGroup>();
        }
    
        public int ID { get; set; }
        public string RequestUrl { get; set; }
        public string RequestHttpType { get; set; }
        public string ActionName { get; set; }
        public System.DateTime SubTime { get; set; }
        public short ActionType { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public virtual ICollection<ActionGroup> ActionGroup { get; set; }
    }
}
