//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYZJ.HM3Shop.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<R_UserInfo_Role> R_UserInfo_Role { get; set; }
        public DbSet<ActionInfo> ActionInfo { get; set; }
        public DbSet<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public DbSet<ActionGroup> ActionGroup { get; set; }
        public DbSet<实体1> 实体1集 { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<GoodInfo> GoodInfo { get; set; }
        public DbSet<Property> Property { get; set; }
        public DbSet<PropOption> PropOption { get; set; }
        public DbSet<GoodsPropValue> GoodsPropValue { get; set; }
        public DbSet<GoodSKU> GoodSKU { get; set; }
        public DbSet<ImageInfo> ImageInfo { get; set; }
        public DbSet<Shop> Shop { get; set; }
    }
}
