//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYZJ.HM3Shop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.PropOption = new HashSet<PropOption>();
            this.Category = new HashSet<Category>();
            this.GoodInfo = new HashSet<GoodInfo>();
        }
    
        public int ID { get; set; }
        public string PropName { get; set; }
        public short ShowType { get; set; }
        public string PropOptions { get; set; }
    
        public virtual ICollection<PropOption> PropOption { get; set; }
        public virtual ICollection<Category> Category { get; set; }
        public virtual ICollection<GoodInfo> GoodInfo { get; set; }
    }
}
