//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NSR_EDIT
    {
        public string ID { get; set; }
        public string NSR_MC { get; set; }
        public string FADDRESS { get; set; }
        public double LON { get; set; }
        public double LAT { get; set; }
        public string ZYZL { get; set; }
        public System.DateTime EDITTIME { get; set; }
        public string XYSYSTEM { get; set; }
    }
}
