//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_QYINFO
    {
        public string SWGLM { get; set; }
        public string NSRSBM { get; set; }
        public string ZZJGTYDM { get; set; }
        public string ZZDM { get; set; }
        public string NSR_MC { get; set; }
        public string SWDJLX { get; set; }
        public string ZCLX { get; set; }
        public string PJSLJG { get; set; }
        public string ZZLB { get; set; }
        public Nullable<System.DateTime> KYSLRQ { get; set; }
        public string ZZLB2 { get; set; }
        public string ZZHM { get; set; }
        public string ZCDZ { get; set; }
        public string ZCDLXDH { get; set; }
        public string SJJYDZ { get; set; }
        public string SCJYDLXDH { get; set; }
        public string HSFS { get; set; }
        public string DWXZ { get; set; }
        public string JYFWZY { get; set; }
        public string GBHY_DM { get; set; }
        public string HYML { get; set; }
        public string HYDL { get; set; }
        public string HYZXL { get; set; }
        public string FRXM { get; set; }
        public string FRZJLX { get; set; }
        public string FRZJ { get; set; }
        public string FRYD_DH { get; set; }
        public string CWXM { get; set; }
        public string CWZJLX { get; set; }
        public string CWZJ { get; set; }
        public string CWYD_DH { get; set; }
        public string BSRXM { get; set; }
        public string BSRZJLX { get; set; }
        public string BSRZJ { get; set; }
        public string BSRYD_DH { get; set; }
        public Nullable<decimal> ZCZB { get; set; }
        public string BZ { get; set; }
        public Nullable<System.DateTime> DSFZ_RQ { get; set; }
        public string DJJGLX { get; set; }
        public string JG_MC { get; set; }
        public string JGNSRSBM { get; set; }
        public string JGZCDZ { get; set; }
        public string JGJYFW { get; set; }
        public string JGFR { get; set; }
        public string XZQHDS { get; set; }
        public string XZQHXQ { get; set; }
        public string XZJD { get; set; }
        public string DLWZZRC { get; set; }
        public string GLJG_DM { get; set; }
        public string GLJG { get; set; }
        public string ZSJG_DM { get; set; }
        public string ZSJG { get; set; }
        public string JIANCJG_DM { get; set; }
        public string JIANCJG { get; set; }
        public string JCJG_DM { get; set; }
        public string JCJG { get; set; }
        public string ZDSYRDBJ { get; set; }
        public string NSRZT_DM { get; set; }
        public string ADDRESS { get; set; }
        public double LON { get; set; }
        public double LAT { get; set; }
        public string LEVEL_NUM { get; set; }
        public string STATUS { get; set; }
        public string FORMATADDRESS { get; set; }
        public string  ID { get; set; }
    }
}
